events {}

http {
  gzip on;
  gzip_types text/plain application/json;

  server {
    listen 80;

    location / {
      proxy_pass http://frontend:3000;
    }

    location /api/ {
      proxy_pass http://backend:8000/;
      proxy_set_header Host $host;
    }
  }
}